= Hello


:hp-tags: Other, Computer Science, iOS

Hello and welcome to my blog!

I'll be writing some posts related to Computer Science here, theoretical or practical(can be referred to code here). Might be more practical stuff as I like to have code to support my points of view. 

For example, in winter 2014, I came up with some new idea of executing malicious code inside other segment of the mach-o formatted executable. I tried to implement it and had to face a lot of restriction in practical. As well as some basic programming skills like memory management. The more funny thing is Apple made some additional security methods on the segments of the executable in autumn 2014, which added more restrictions to my thought, but it is fun to solve problems.

Besides, I am keen on "reconstructing wheels" for now. In the above example, I wrote my own mach-o file reader to support some malicious code replacements. I think all the reconstruction I have done make me a more experienced programmer, and for many CS materials I've been taught, implement them on my own helped me understand the theory better. 

In conclusion of my expectation, all of my posts will not be so rigorous and worth worthy for you to read, the key purpose is to record and share some experiences of me.

Also, I'm very willing to meet new friends.

新浪微博: *0xSuu*