= How to chat securely

:hp-tags: Other, RSA, Safety, Encryption


With people who want to sniff your privacy all around you, with what method you can keep message transferring safe, even you disclose your messages to public and only your target receiver can understand it? 

The answer is Public Key Encryption, or Asymmetric Encryption. If you image symmetric encryption as crafting a lock with one unique key. With asymmetric encryption, you hold two keys, one for encryption, one for decryption. The decryption key is the only key to open the lock crafted with the encryption key(encoding). So once your target person send you his encryption key, you could do nothing but encrypting your message with that key, so you did it, and you published the encrypted message and your target would be the only one that able to decrypt the message.

Below is few lines of code make those encryption and decryption easier. If you are not on Mac, please uncomment last two lines because those are for copying encrypted message automatically with some apple script.

```Python
